### Get All Products
GET http://localhost:5000/products

### Get Product By ID
GET http://localhost:5000/products/1

### Create Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Logitech G Pro",
    "category": "Elektronik",
    "price": 1500000,
    "stock": 10
}

### Update Product
PATCH http://localhost:5000/products/4
Content-Type: application/json

{
    "name": "Sepatu Lari Pro",
    "category": "Sepatu",
    "price": 850000,
    "stock": 8
}

### Delete Product
DELETE http://localhost:5000/products/3